project:
  type: book
  output-dir: docs

book:
  title: "Computational Probability and Statistics"
  reader-mode: true
  page-footer:
    left: |
      Computation Probability and Statistics by Hitt, Horton, and Warner
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  author:
    - Bradley Warner
    - Brianna Hitt 
    - Ken Horton
  date: now
  repo-url: https://github.com/DS-USAFA/Quarto-Book
  repo-actions: edit
  chapters: 
    - index.qmd
    - 00-Objectives.qmd
    - part: "Descriptive Statistical Modeling"
      chapters:
        - Data-Case-Study.qmd
        - Data-Basics.qmd
        - Overview-of-Data-Collection-Principles.qmd
        - Studies.qmd
        - Numerical-Data.qmd
        - Categorical-Data.qmd
    - part: "Probability Modeling"
      chapters:
        - Probability-Case-Study.qmd
        - Probability-Rules.qmd
        - Conditional-Probability.qmd
        - Discrete-Random-Variables.qmd
        - Continuous-Random-Variables.qmd
        - Named-Discrete-Distributions.qmd
        - Named-Continuous-Distributions.qmd
    - part: "Advanced Probability"
      chapters:   
        - Multivariate-Distributions.qmd     
        - Multivariate-Expectation.qmd
        - Transformations.qmd
        - Estimation-Methods.qmd
    - part: "Statistical Modeling - Inference"
      chapters:  
        - Inference-Case-Study.qmd
        - Sampling-Distributions.qmd
        - Bootstrap.qmd
        - Hypothesis-Testing-Simulation.qmd
        - Hypothesis-Testing-ProbDist.qmd
        - Central-Limit-Theorem.qmd
        - Confidence-Intervals.qmd
        - Additional-Hypothesis-Tests.qmd
        - Analysis-of-Variance.qmd
    - part: "Statistical Modeling - Prediction"
      chapters:  
        - Linear-Regression-Case-Study.qmd
        - Linear-Regression-Basics.qmd
        - Linear-Regression-Inference.qmd
        - Linear-Regression-Diagnostics.qmd
        - Simulation-Based-Linear-Regression.qmd
        - Multiple-Linear-Regression.qmd
        - Logistic-Regression.qmd
cover-image: Cover_Majors.png
favicon: Cover_Majors.png
biblio-style: apalike
bibliography: [book.bib, packages.bib, references.bib]


format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
#    toc-expand: true
  pdf:
    documentclass: scrreprt

editor: visual

