<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>25&nbsp; Additional Hypothesis Tests – Computational Probability and Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Analysis-of-Variance.html" rel="next">
<link href="./Confidence-Intervals.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Inference-Case-Study.html">Statistical Modeling - Inference</a></li><li class="breadcrumb-item"><a href="./Additional-Hypothesis-Tests.html"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Additional Hypothesis Tests</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Computational Probability and Statistics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/DS-USAFA/Quarto-Book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-Objectives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Objectives</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Descriptive Statistical Modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Data-Case-Study.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data Case Study</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Data-Basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Overview-of-Data-Collection-Principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Overview of Data Collection Principles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Studies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Studies</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Numerical-Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Numerical Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Categorical-Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Categorical Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Probability Modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Probability-Case-Study.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Probability Case Study</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Probability-Rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability Rules</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Conditional-Probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Conditional Probability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Discrete-Random-Variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Discrete Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Continuous-Random-Variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Continuous Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Named-Discrete-Distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Named Discrete Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Named-Continuous-Distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Named Continuous Distributions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Advanced Probability</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Multivariate-Distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Multivariate Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Multivariate-Expectation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Multivariate Expectation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Transformations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Estimation-Methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Estimation Methods</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical Modeling - Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Inference-Case-Study.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inferential Thinking Case Study</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Sampling-Distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Sampling Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Bootstrap</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Hypothesis-Testing-Simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Hypothesis Testing with Simulation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Hypothesis-Testing-ProbDist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Hypothesis Testing with Known Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Central-Limit-Theorem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Hypothesis Testing with the Central Limit Theorem</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Confidence-Intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Additional-Hypothesis-Tests.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Additional Hypothesis Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Analysis-of-Variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical Modeling - Prediction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Linear-Regression-Case-Study.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Linear Regression Case Study</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Linear-Regression-Basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Linear Regression Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Linear-Regression-Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Linear Regression Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Linear-Regression-Diagnostics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Regression Diagnostics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Simulation-Based-Linear-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Simulation-Based Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Multiple-Linear-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Logistic-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Logistic Regression</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#objectives" id="toc-objectives" class="nav-link active" data-scroll-target="#objectives"><span class="header-section-number">25.1</span> Objectives</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">25.2</span> Introduction</a></li>
  <li><a href="#other-distributions-for-estimators" id="toc-other-distributions-for-estimators" class="nav-link" data-scroll-target="#other-distributions-for-estimators"><span class="header-section-number">25.3</span> Other distributions for estimators</a>
  <ul class="collapse">
  <li><a href="#chi-squared" id="toc-chi-squared" class="nav-link" data-scroll-target="#chi-squared"><span class="header-section-number">25.3.1</span> Chi-squared</a></li>
  <li><a href="#important-note" id="toc-important-note" class="nav-link" data-scroll-target="#important-note"><span class="header-section-number">25.3.2</span> Important Note</a></li>
  </ul></li>
  <li><a href="#categorical-data" id="toc-categorical-data" class="nav-link" data-scroll-target="#categorical-data"><span class="header-section-number">25.4</span> Categorical data</a>
  <ul class="collapse">
  <li><a href="#health-evaluation-and-linkage-to-primary-care" id="toc-health-evaluation-and-linkage-to-primary-care" class="nav-link" data-scroll-target="#health-evaluation-and-linkage-to-primary-care"><span class="header-section-number">25.4.1</span> Health evaluation and linkage to primary care</a></li>
  <li><a href="#test-statistic" id="toc-test-statistic" class="nav-link" data-scroll-target="#test-statistic"><span class="header-section-number">25.4.2</span> Test statistic</a></li>
  <li><a href="#extension-to-larger-tables" id="toc-extension-to-larger-tables" class="nav-link" data-scroll-target="#extension-to-larger-tables"><span class="header-section-number">25.4.3</span> Extension to larger tables</a></li>
  <li><a href="#test-statistic-for-the-help-example" id="toc-test-statistic-for-the-help-example" class="nav-link" data-scroll-target="#test-statistic-for-the-help-example"><span class="header-section-number">25.4.4</span> Test statistic for the HELP example</a></li>
  <li><a href="#calculate-the-p-value" id="toc-calculate-the-p-value" class="nav-link" data-scroll-target="#calculate-the-p-value"><span class="header-section-number">25.4.5</span> Calculate the <span class="math inline">\(p\)</span>-value</a></li>
  <li><a href="#permutation-test" id="toc-permutation-test" class="nav-link" data-scroll-target="#permutation-test"><span class="header-section-number">25.4.6</span> Permutation test</a></li>
  </ul></li>
  <li><a href="#numerical-data" id="toc-numerical-data" class="nav-link" data-scroll-target="#numerical-data"><span class="header-section-number">25.5</span> Numerical data</a>
  <ul class="collapse">
  <li><a href="#mlb-batting-performance" id="toc-mlb-batting-performance" class="nav-link" data-scroll-target="#mlb-batting-performance"><span class="header-section-number">25.5.1</span> MLB batting performance</a></li>
  <li><a href="#two-sample-t-test-in-r" id="toc-two-sample-t-test-in-r" class="nav-link" data-scroll-target="#two-sample-t-test-in-r"><span class="header-section-number">25.5.2</span> Two-sample <span class="math inline">\(t\)</span>-test in <code>R</code></a></li>
  <li><a href="#randomization-test" id="toc-randomization-test" class="nav-link" data-scroll-target="#randomization-test"><span class="header-section-number">25.5.3</span> Randomization test</a></li>
  <li><a href="#paired-data" id="toc-paired-data" class="nav-link" data-scroll-target="#paired-data"><span class="header-section-number">25.5.4</span> Paired data</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/DS-USAFA/Quarto-Book/edit/main/Additional-Hypothesis-Tests.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Inference-Case-Study.html">Statistical Modeling - Inference</a></li><li class="breadcrumb-item"><a href="./Additional-Hypothesis-Tests.html"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Additional Hypothesis Tests</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-ADDTESTS" class="quarto-section-identifier"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Additional Hypothesis Tests</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="objectives" class="level2" data-number="25.1">
<h2 data-number="25.1" class="anchored" data-anchor-id="objectives"><span class="header-section-number">25.1</span> Objectives</h2>
<ol type="1">
<li><p>Conduct and interpret a goodness of fit test using both Pearson’s chi-squared and randomization to evaluate the independence between two categorical variables. Evaluate the assumptions for Pearson’s chi-square test.</p></li>
<li><p>Analyze the relationship between the chi-squared and normal distributions, explain usage contexts, and evaluate the effects of changing degrees of freedom on the chi-squared distribution using visualizations.</p></li>
<li><p>Conduct and interpret a hypothesis test for equality of two means and equality of two variances using both permutation and the CLT. Evaluate the assumptions for two-sample t-tests.</p></li>
</ol>
</section>
<section id="introduction" class="level2" data-number="25.2">
<h2 data-number="25.2" class="anchored" data-anchor-id="introduction"><span class="header-section-number">25.2</span> Introduction</h2>
<p>The purpose of the next two chapters is to put all we’ve learned so far in this block into perspective, and to demonstrate a couple of new statistical tests.</p>
<p>Remember that we have been using data to answer research questions. So far, we can do this with hypothesis tests, using several different methods. There is a close link between these methods, and the steps of hypothesis testing have remained the same no matter which method is used. The key ideas have been to generate a single number metric to use in answering our research question, and then to obtain the sampling distribution of this metric.</p>
<p>In obtaining the sampling distribution, we used randomization as an approximation to permutation exact tests, probability models, and mathematical models. Each of these had different assumptions and different areas where they could be applied. In some cases, several methods can be applied to the problem to get a sense of the robustness to different assumptions. For example, if you run a randomization test and a test using the CLT, and they both give you similar results, you can feel better about your decision.</p>
<p>Finding a single number metric to answer our research question can be difficult. For example, in <a href="Hypothesis-Testing-Simulation.html" class="quarto-xref"><span>Chapter 21</span></a>, we wanted to determine if the distribution of lengths of commercials for premium and basic channels was different. The difference in means has been used for historical reasons, and we now know that is because of the need to use the <span class="math inline">\(t\)</span> distribution. But is this the best way to answer the question? Because we wanted to think creatively, we ended up using the ratio of median lengths as our single number metric. However, there are other ways in which the distribution of lengths of commercials can differ.</p>
<p>Jack Welch was the CEO of GE for years and he made the claim that customers don’t care about the average, but they do care about variability. The average temperature setting of your GE refrigerator could be off and you would adapt. However, if the temperature had great variability, then you would be upset. So metrics that incorporate variability might be good. In <a href="Hypothesis-Testing-Simulation.html" class="quarto-xref"><span>Chapter 21</span></a>, we looked at the length of commercials for basic and premium TV channels. In using a randomization test, we assumed in the null hypothesis that there was no difference in the distributions. However, in the alternative hypothesis, we measured the difference in distributions using only medians, a measure of average. The medians of these two populations could be equal, but the distributions could differ in other ways, like variability. We could conduct a separate test for variances, but we have to be careful about multiple comparisons because, in that case, the Type 1 error is inflated.</p>
<p>We also learned that the use of the information in the data impacts the power of the test. In the golf ball example in <a href="Hypothesis-Testing-ProbDist.html" class="quarto-xref"><span>Chapter 22</span></a>, using range as our metric did not give the same power as looking at the differences from expected values under the null hypothesis. There is some mathematical theory, called likelihood ratio tests, that leads to better estimators, but it is beyond the scope of this book. What you can do is create a simulation where you generate data from the alternative hypothesis and then measure the power. This will give you a sense of the quality of your metric. We only briefly looked at measuring power in <a href="Hypothesis-Testing-ProbDist.html" class="quarto-xref"><span>Chapter 22</span></a> and will not go further into this idea in this chapter.</p>
<p>We will continue this block by examining problems with two variables. In the first case, both variables will be categorical and at least one of the categorical variables will have more than two levels. In the second case, we will examine two variables, where one is numeric and the other is categorical, and the categorical variable has more than two levels.</p>
</section>
<section id="other-distributions-for-estimators" class="level2" data-number="25.3">
<h2 data-number="25.3" class="anchored" data-anchor-id="other-distributions-for-estimators"><span class="header-section-number">25.3</span> Other distributions for estimators</h2>
<p>In <a href="Central-Limit-Theorem.html" class="quarto-xref"><span>Chapter 23</span></a>, we discussed the <span class="math inline">\(t\)</span> distribution, a different sampling distribution that is based on the CLT or normality assumption. In theoretical statistics, we often mathematically derive the sampling distribution by obtaining a sample statistic, determining the distribution of that statistic under certain conditions, and using that information to make a statement about the population parameter. We now discuss another commonly used sampling distribution: the chi-squared distribution.</p>
<section id="chi-squared" class="level3" data-number="25.3.1">
<h3 data-number="25.3.1" class="anchored" data-anchor-id="chi-squared"><span class="header-section-number">25.3.1</span> Chi-squared</h3>
<p>Recall the central limit theorem tells us that for reasonably large sample sizes, <span class="math inline">\(\bar{X} \overset{approx}{\sim} \textsf{Norm}(\mu, \sigma/\sqrt{n})\)</span>. This expression involves two unknowns: <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>. In the case of binary data, the population variance is a function of the population proportion <span class="math inline">\(\left(Var(X)=\pi(1-\pi)\right)\)</span>, so there is really just one unknown, the population mean <span class="math inline">\(\pi\)</span>. This can be estimated with the sample proportion, <span class="math inline">\(p\)</span>.</p>
<p>In the case of continuous data, the population mean can be estimated with <span class="math inline">\(\bar{x}\)</span>. The population variance would need to be estimated as well. Let <span class="math inline">\(S^2\)</span> be defined as:</p>
<p><span class="math display">\[
S^2 = {\sum (X_i - \bar{X})^2 \over n - 1}
\]</span></p>
<p>This is an unbiased estimate for <span class="math inline">\(\sigma^2\)</span>, meaning that, on average, the estimator above will equal the true value we are trying to estimate (i.e., the true population variance). The sampling distribution of <span class="math inline">\(S^2\)</span> can be found using the following lemma.</p>
<blockquote class="blockquote">
<p>Lemma: Let <span class="math inline">\(X_1, X_2, ..., X_n\)</span> be an i.i.d. sequence of random variables from a normal population with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span>. Then,<br>
<span class="math display">\[
{(n-1) S^2\over \sigma^2} \sim \textsf{Chisq}(n - 1)
\]</span></p>
</blockquote>
<p>The <span class="math inline">\(\textsf{Chisq}(n-1)\)</span> distribution is read as the “chi-squared” distribution (“chi” is pronounced “kye”). This can also be written as <span class="math inline">\(\chi^2 (n-1)\)</span>. The chi-squared distribution has one parameter: degrees of freedom. The chi-squared distribution is used in other contexts such as goodness of fit problems, like the golf ball example from <a href="Hypothesis-Testing-ProbDist.html" class="quarto-xref"><span>Chapter 22</span></a>.</p>
<p>The proof of this lemma is outside the scope of this book, but it is not terribly complicated. It follows from the fact that the sum of <span class="math inline">\(n\)</span> squared random variables, each with the standard normal distribution, follows the chi-squared distribution with <span class="math inline">\(n\)</span> degrees of freedom.</p>
<p>This lemma can be used to draw inferences about <span class="math inline">\(\sigma^2\)</span>. For a particular value of <span class="math inline">\(\sigma^2\)</span>, we know how <span class="math inline">\(S^2\)</span> should behave. So, for a particular value of <span class="math inline">\(S^2\)</span>, we can figure out reasonable values of <span class="math inline">\(\sigma^2\)</span>. In practice, one rarely estimates <span class="math inline">\(\sigma\)</span> for the purpose of inference on <span class="math inline">\(\sigma\)</span>. Typically, we are interested in estimating <span class="math inline">\(\mu\)</span> and we need to account for the added uncertainty by estimating <span class="math inline">\(\sigma\)</span> as well.</p>
<p>The chi-squared distribution takes on positive values and is right skewed. The degrees of freedom influence the shape and location of the distribution. As the degrees of freedom increase, it becomes more similar to a normal distribution. That is, the distribution becomes more symmetric with larger variability, and the center of the distribution moves to the right. <a href="#fig-chisq221" class="quarto-xref">Figure&nbsp;<span>25.1</span></a> demonstrates these trends.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-chisq221" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-chisq221-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Additional-Hypothesis-Tests_files/figure-html/fig-chisq221-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chisq221-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;25.1: Chi-square distribution for different degrees of freedom.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="important-note" class="level3" data-number="25.3.2">
<h3 data-number="25.3.2" class="anchored" data-anchor-id="important-note"><span class="header-section-number">25.3.2</span> Important Note</h3>
<p>Just like for the <span class="math inline">\(t\)</span> distribution, the lemma above assumed that each <span class="math inline">\(X_i\)</span> in the sequence of random variables was <em>normally</em> distributed. While the central limit theorem has no such normality assumption, the distribution of the chi-square statistic is subject to the distribution of the underlying population. With large enough expected counts, this assumption is not necessary. Again, there is no magic number, but some resources state that no expected count should be less than one and no more than 20% of the expected counts should be less than five.</p>
<p>One advantage of simulation-based inference methods is that these methods do not rely on any such distributional assumptions. However, the simulation-based methods may have smaller power for the same sample size.</p>
</section>
</section>
<section id="categorical-data" class="level2" data-number="25.4">
<h2 data-number="25.4" class="anchored" data-anchor-id="categorical-data"><span class="header-section-number">25.4</span> Categorical data</h2>
<p>It is worth spending some time on common approaches to categorical data that you may come across. We have already dealt with categorical data to some extent in this book. We have performed hypothesis tests for <span class="math inline">\(\pi\)</span>, the population proportion of “success” in binary cases (for example, support for a local measure in a vote). This problem had a single variable. Also, the golf ball example involved counts of four types of golf ball. This is considered categorical data because each observation is characterized by a qualitative value (number on the ball). The data are summarized by counting how many balls in a sample belong to each type. This again was a single variable.</p>
<p>In another scenario, suppose we are presented with two qualitative variables and would like to know if they are independent. For example, in <a href="Hypothesis-Testing-Simulation.html" class="quarto-xref"><span>Chapter 21</span></a>, we discussed methods for determining whether there was a relationship between blood thinners and survival in patients who received CPR for a heart attack. In this case, we have two categorical variables with two levels each: receiving a blood thinner (treatment vs control) and survival (survived vs died). We have solved this type of problem by looking at a difference in probabilities of survival using randomization and mathematically derived solutions, the CLT. We have also used a hypergeometric distribution to obtain an exact <span class="math inline">\(p\)</span>-value.</p>
<p>We will next explore a scenario that involves categorical data with two variables but where at least one variable has more than two levels. However, note that we are only merely scratching the surface in our studies. You could take an entire course on statistical methods for categorical data. This book is giving you a solid foundation to learn more advanced methods.</p>
<section id="health-evaluation-and-linkage-to-primary-care" class="level3" data-number="25.4.1">
<h3 data-number="25.4.1" class="anchored" data-anchor-id="health-evaluation-and-linkage-to-primary-care"><span class="header-section-number">25.4.1</span> Health evaluation and linkage to primary care</h3>
<p>The Health Evaluation and Linkage to Primary Care (HELP) study was a clinical trial for adult inpatients recruited from a detoxification unit. Patients with no primary care physician were randomized to receive a multidisciplinary assessment and a brief motivational intervention or usual care, with the goal of linking them to primary medical care.</p>
<p>The <code>HELPrct</code> data set is available in the <strong>mosaicData</strong> package. There are three substances: alcohol, cocaine, and heroin. We’d like to know if there is evidence that the proportions of use for <code>substance</code>, the primary substance of abuse, differ for males and females.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HELPrct"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>HELP_sub <span class="ot">&lt;-</span> HELPrct <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(substance, sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(substance <span class="sc">~</span> sex, <span class="at">data =</span> HELPrct, <span class="at">format =</span> <span class="st">"prop"</span>, <span class="at">margins =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         sex
substance    female      male
  alcohol 0.3364486 0.4075145
  cocaine 0.3831776 0.3208092
  heroin  0.2803738 0.2716763
  Total   1.0000000 1.0000000</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-props222" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-props222-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Additional-Hypothesis-Tests_files/figure-html/fig-props222-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-props222-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;25.2: Proportions for primary substance of abuse in the HELP study, faceted by sex.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-props223" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-props223-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Additional-Hypothesis-Tests_files/figure-html/fig-props223-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-props223-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;25.3: The distribution of primary substance of abuse in the HELP study by sex.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The two-way table and <a href="#fig-props222" class="quarto-xref">Figure&nbsp;<span>25.2</span></a> and <a href="#fig-props223" class="quarto-xref">Figure&nbsp;<span>25.3</span></a> exhibit modest differences in the primary substance of abuse by sex, but is it statistically significant?</p>
<p>We need a test statistic to determine if there is a difference in primary substance of abuse between males and females.</p>
</section>
<section id="test-statistic" class="level3" data-number="25.4.2">
<h3 data-number="25.4.2" class="anchored" data-anchor-id="test-statistic"><span class="header-section-number">25.4.2</span> Test statistic</h3>
<p>To help us develop and understand a test statistic, let’s simplify and use a simple theoretical example.</p>
<p>Suppose we have a 2 x 2 contingency table like the one below.</p>
<p><span class="math display">\[
\begin{array}{lcc}
&amp; \mbox{Response 1} &amp; \mbox{Response 2} \\
\mbox{Group 1} &amp; n_{11} &amp; n_{12} \\
\mbox{Group 2} &amp; n_{21} &amp; n_{22}
\end{array}
\]</span></p>
<p>If our null hypothesis is that the two variables are independent, a classical test statistic used is the Pearson chi-squared test statistic (<span class="math inline">\(X^2\)</span>). This is similar to the test statistic we used in our golf ball example in <a href="Hypothesis-Testing-ProbDist.html" class="quarto-xref"><span>Chapter 22</span></a>. Let <span class="math inline">\(e_{ij}\)</span> be the expected count in the <span class="math inline">\(i\)</span>th row and <span class="math inline">\(j\)</span>th column under the null hypothesis. Then the test statistic is the squared difference of the observed and expected counts, divided by the expected count, summed over both levels of each categorical variable. This expression is shown below:</p>
<p><span class="math display">\[
X^2 = \sum_{i = 1}^2 \sum_{j = 1}^2 {(n_{ij} - e_{ij})^2 \over e_{ij}}
\]</span></p>
<p>But how do we find <span class="math inline">\(e_{ij}\)</span>, the expected count, for each cell? What do we expect the count to be under <span class="math inline">\(H_0\)</span>?</p>
<p>To find the expected counts, we recognize that under <span class="math inline">\(H_0\)</span> (independence), a joint probability is equal to the product of the marginal probabilities. Let <span class="math inline">\(\pi_{ij}\)</span> be the probability of an outcome occurring in row <span class="math inline">\(i\)</span> and column <span class="math inline">\(j\)</span>. In the absence of any other information, our best guess at <span class="math inline">\(\pi_{ij}\)</span> is <span class="math inline">\(\hat{\pi}_{ij} = {n_{ij}\over n}\)</span>, where <span class="math inline">\(n_{ij}\)</span> is the number of observations occurring in row <span class="math inline">\(i\)</span> and column <span class="math inline">\(j\)</span>, and <span class="math inline">\(n\)</span> is the total sample size for the entire table. But under the null hypothesis, we have the assumption of independence. Thus, <span class="math inline">\(\pi_{ij} = \pi_{i+} \pi_{+j}\)</span> where <span class="math inline">\(\pi_{i+}\)</span> represents the total probability of occurring in row <span class="math inline">\(i\)</span> and <span class="math inline">\(\pi_{+j}\)</span> represents the total probability of occurring in column <span class="math inline">\(j\)</span>. Note that <span class="math inline">\(\pi_{i+}\)</span> is estimated by <span class="math inline">\(\hat{\pi}_{i+}\)</span> and</p>
<p><span class="math display">\[
\hat{\pi}_{i+} = {n_{i+}\over n},
\]</span></p>
<p>where <span class="math inline">\(n_{i+}\)</span> is the sample size for row <span class="math inline">\(i\)</span>. This can be found by summing the sample size for all cells in row <span class="math inline">\(i\)</span>.</p>
<p>Thus for our simple 2 x 2 example, we have:</p>
<p><span class="math display">\[
\hat{\pi}_{i+} = {n_{i+}\over n} = {n_{i1}+n_{i2}\over n}
\]</span></p>
<p>Thus, for Group 1 we would have:</p>
<p><span class="math display">\[
\hat{\pi}_{1+} = {n_{1+}\over n} = {n_{11}+n_{12}\over n}
\]</span></p>
<p>So, under <span class="math inline">\(H_0\)</span>, our best guess for <span class="math inline">\(\pi_{ij}\)</span> is:</p>
<p><span class="math display">\[
\hat{\pi}_{ij} = \hat{\pi}_{i+}\hat{\pi}_{+j} = {n_{i+}\over n}{n_{+j}\over n} = {n_{i1}+n_{i2}\over n}{n_{1j}+n_{2j}\over n}
\]</span></p>
<p>Continuing, under <span class="math inline">\(H_0\)</span> the expected cell count is:</p>
<p><span class="math display">\[
e_{ij} = n\hat{\pi}_{ij} = n{n_{i+}\over n}{n_{+j}\over n} = {n_{i+}n_{+j}\over n}
\]</span></p>
<p>This is essentially found by multiplying the row total (the sample size for row <span class="math inline">\(i\)</span>) by the column total (the sample size for column <span class="math inline">\(j\)</span>) and dividing by the overall table total (the total sample size, <span class="math inline">\(n\)</span>).</p>
</section>
<section id="extension-to-larger-tables" class="level3" data-number="25.4.3">
<h3 data-number="25.4.3" class="anchored" data-anchor-id="extension-to-larger-tables"><span class="header-section-number">25.4.3</span> Extension to larger tables</h3>
<p>The advantage of using the Pearson chi-squared test statistic is that it can easily be extended to larger <strong>contingency tables</strong>, the name given to these tables displaying multiple categorical variables. Suppose we are comparing two categorical variables, one with <span class="math inline">\(r\)</span> levels and the other with <span class="math inline">\(c\)</span> levels. Then,</p>
<p><span class="math display">\[
X^2 = \sum_{i=1}^r \sum_{j=1}^c {(n_{ij} - e_{ij})^2\over e_{ij}}
\]</span></p>
<p>This is exactly the same as before, except that instead of summing over two levels of each categorical variable, we sum over all <span class="math inline">\(r\)</span> and <span class="math inline">\(c\)</span> levels. That is, we sum over all cells in the contingency table.</p>
<p>Under the null hypothesis of independence, the <span class="math inline">\(X^2\)</span> test statistic follows the chi-squared distribution with <span class="math inline">\((r-1)\times(c-1)\)</span> degrees of freedom.</p>
<section id="assumptions" class="level4" data-number="25.4.3.1">
<h4 data-number="25.4.3.1" class="anchored" data-anchor-id="assumptions"><span class="header-section-number">25.4.3.1</span> Assumptions</h4>
<p>Note that to use this test statistic, the expected cell counts, each <span class="math inline">\(e_{ij}\)</span>, must be reasonably large. In fact, no <span class="math inline">\(e_{ij}\)</span> should be less than one and no more than 20% of the <span class="math inline">\(e_{ij}\)</span>’s should be less than five. If this occurs, we should combine cells or look for a different test.</p>
<p>This may all look too abstract, so let’s break it down with an example.</p>
</section>
</section>
<section id="test-statistic-for-the-help-example" class="level3" data-number="25.4.4">
<h3 data-number="25.4.4" class="anchored" data-anchor-id="test-statistic-for-the-help-example"><span class="header-section-number">25.4.4</span> Test statistic for the HELP example</h3>
<p>Let’s return to the Health Evaluation and Linkage to Primary Care data set. There are two levels of the <code>sex</code> variable, female and male. There are three levels of the <code>substance</code> variable: alcohol, cocaine, and heroin. A two-way contingency table is shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(<span class="sc">~</span>substance <span class="sc">+</span> sex, <span class="at">data =</span> HELPrct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         sex
substance female male
  alcohol     36  141
  cocaine     41  111
  heroin      30   94</code></pre>
</div>
</div>
<p>To find the Pearson chi-squared test statistic (<span class="math inline">\(X^2\)</span>), we need to figure out the expected count for each cell, <span class="math inline">\(e_{ij}\)</span>, under <span class="math inline">\(H_0\)</span>. Recall that under <span class="math inline">\(H_0\)</span>, the two variables are independent. It’s helpful to add the row and column totals prior to finding expected counts:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(<span class="sc">~</span>substance <span class="sc">+</span> sex, <span class="at">data =</span> HELPrct, <span class="at">margins =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         sex
substance female male Total
  alcohol     36  141   177
  cocaine     41  111   152
  heroin      30   94   124
  Total      107  346   453</code></pre>
</div>
</div>
<p>Under the assumption of independence, <span class="math inline">\(H_0\)</span>, the expected count for each cell is equal to the row sum multiplied by the column sum divided by the overall table sum. So, the expected count for the cell representing females who abuse alcohol is</p>
<p><span class="math display">\[
e_{11} = {177*107 \over 453} = 41.81
\]</span></p>
<p>Continuing in this fashion yields the following table of expected counts:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         sex
substance   female      male
  alcohol 41.80795 135.19205
  cocaine 35.90287 116.09713
  heroin  29.28918  94.71082</code></pre>
</div>
</div>
<p>Now, we can find the value of the test statistic, <span class="math inline">\(X^2\)</span>:</p>
<span class="math display">\[\begin{multline}
X^2 = {(36 - 41.81)^2 \over 41.81} + {(141 - 135.19)^2 \over 135.19} + {(41 - 35.90)^2 \over 35.90} \\ + {(111 - 116.10)^2 \over 116.10} + {(30 - 29.29)^2 \over 29.29} + {(94 - 94.71)^2 \over 94.71}
\end{multline}\]</span>
<p>As you can probably tell, <span class="math inline">\(X^2\)</span> is essentially comparing the observed counts with the expected counts under <span class="math inline">\(H_0\)</span>. The larger the difference between observed and expected count, the larger the value of <span class="math inline">\(X^2\)</span>. It is normalized by dividing by the expected counts since more data in a cell leads to a larger contribution to the sum. Under <span class="math inline">\(H_0\)</span>, this statistic follows the chi-squared distribution with <span class="math inline">\((r-1)\times(c-1)\)</span> degrees of freedom (<span class="math inline">\(r\)</span> is the number of rows and <span class="math inline">\(c\)</span> is the number of columns). In our example, we have <span class="math inline">\((3 - 1)\times (2 - 1) = 2\)</span> degrees of freedom.</p>
</section>
<section id="calculate-the-p-value" class="level3" data-number="25.4.5">
<h3 data-number="25.4.5" class="anchored" data-anchor-id="calculate-the-p-value"><span class="header-section-number">25.4.5</span> Calculate the <span class="math inline">\(p\)</span>-value</h3>
<p>We can find the Pearson chi-squared test statistic (<span class="math inline">\(X^2\)</span>) and corresponding <span class="math inline">\(p\)</span>-value from the chi-squared distribution in <code>R</code> in a couple of different ways. If we had to enter the data in <code>R</code>, we could simply create vectors of the expected and observed counts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>o <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">36</span>, <span class="dv">141</span>, <span class="dv">41</span>, <span class="dv">111</span>, <span class="dv">30</span>, <span class="dv">94</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>e <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">41.81</span>, <span class="fl">135.19</span>, <span class="fl">35.90</span>, <span class="fl">116.10</span>, <span class="fl">29.29</span>, <span class="fl">94.71</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">sum</span>((o <span class="sc">-</span> e)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> e)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>x2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.02814</code></pre>
</div>
</div>
<p>Note that the chi-squared test statistic is a sum of squared differences. Thus, its distribution, a chi-squared distribution, is skewed right and bounded on the left at zero. A departure from the null hypothesis means larger differences between observed and expected counts, and hence, a larger test statistic value. That is, a value further in the right tail of the distribution. Thus, we find the <span class="math inline">\(p\)</span>-value by calculating the probability in the upper tail of the chi-square distribution. We do this by subtracting the CDF from one.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(x2, <span class="at">df =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3627397</code></pre>
</div>
</div>
<p>The large <span class="math inline">\(p\)</span>-value suggests there is not enough evidence to say these two variables are dependent.</p>
<p>Of course, there is also a built-in function in <code>R</code> that will make the calculations easier. It is <code>chisq.test()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(<span class="sc">~</span>substance <span class="sc">+</span> sex, <span class="at">data =</span> HELPrct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         sex
substance female male
  alcohol     36  141
  cocaine     41  111
  heroin      30   94</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">tally</span>(<span class="sc">~</span>substance <span class="sc">+</span> sex, <span class="at">data =</span> HELPrct), <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tally(~substance + sex, data = HELPrct)
X-squared = 2.0264, df = 2, p-value = 0.3631</code></pre>
</div>
</div>
<p>We can extract just the table of expected counts:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">tally</span>(<span class="sc">~</span>substance <span class="sc">+</span> sex, <span class="at">data =</span> HELPrct), <span class="at">correct =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>expected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         sex
substance   female      male
  alcohol 41.80795 135.19205
  cocaine 35.90287 116.09713
  heroin  29.28918  94.71082</code></pre>
</div>
</div>
<p>We can also extract just the test statistic, which we will for permutation tests:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">tally</span>(<span class="sc">~</span>substance <span class="sc">+</span> sex, <span class="at">data =</span> HELPrct), <span class="at">correct =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>statistic</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>X-squared 
 2.026361 </code></pre>
</div>
</div>
<p>We can calculate just the test statistic by using the <code>chisq()</code> function as well:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq</span>(<span class="sc">~</span>substance <span class="sc">+</span> sex, <span class="at">data =</span> HELPrct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>X.squared 
 2.026361 </code></pre>
</div>
</div>
</section>
<section id="permutation-test" class="level3" data-number="25.4.6">
<h3 data-number="25.4.6" class="anchored" data-anchor-id="permutation-test"><span class="header-section-number">25.4.6</span> Permutation test</h3>
<p>We will complete our analysis of the HELP data using a randomization, or approximate permutation, test. First, let’s write the hypotheses:</p>
<p><span class="math inline">\(H_0\)</span>: The variables sex and substance are independent.<br>
<span class="math inline">\(H_a\)</span>: The variables sex and substance are dependent.</p>
<p>We will use the chi-squared test statistic as our test statistic for the randomization test. We could use a different test statistic, such as the absolute value function instead of the square function, but then we would need to write a custom function.</p>
<p>Let’s calculate the observed value of the test statistic:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> <span class="fu">chisq</span>(substance <span class="sc">~</span> sex, <span class="at">data =</span> HELPrct)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>obs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>X.squared 
 2.026361 </code></pre>
</div>
</div>
<p>Notice that we can also use <code>chisq(~substance + sex, data = HELPrct)</code> to get the same result.</p>
<p>Next, we will use a randomization process to find the sampling distribution of our test statistic.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2720</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">1000</span>)<span class="sc">*</span><span class="fu">chisq</span>(substance <span class="sc">~</span> <span class="fu">shuffle</span>(sex), <span class="at">data =</span> HELPrct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><a href="#fig-hist224" class="quarto-xref">Figure&nbsp;<span>25.4</span></a> is a visual summary of the results, which helps us to gain some intuition about the <span class="math inline">\(p\)</span>-value. We also plot the theoretical chi-squared distribution as a dark blue overlay. The observed test statistic value is shown as a red line.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-hist224" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hist224-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Additional-Hypothesis-Tests_files/figure-html/fig-hist224-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hist224-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;25.4: Sampling distribution of chi-squared test statistic from randomization test.
</figcaption>
</figure>
</div>
</div>
</div>
<p>We find the <span class="math inline">\(p\)</span>-value using <code>prop1()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop1</span>((<span class="sc">~</span>X.squared <span class="sc">&gt;=</span> obs), <span class="at">data =</span> results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>prop_TRUE 
0.3536464 </code></pre>
</div>
</div>
<p>We don’t double this value because the chi-squared test is a one-sided test, due to the fact that we squared the differences. A departure from the null hypothesis means larger differences between observed and expected counts, and hence, a larger test statistic value. Thus, we are only interested in the upper (right) tail of the distribution.</p>
<p>Based on this <span class="math inline">\(p\)</span>-value, we fail to reject the null hypothesis that the variables are independent. This <span class="math inline">\(p\)</span>-value is very similar to the <span class="math inline">\(p\)</span>-value we found in the previous section for the Pearson’s chi-squared test, leading us to the same conclusion.</p>
<p>Note that in the randomization test, we shuffled the variable <code>sex</code> over many replications and calculated a value of the test statistic for each replication. We did this shuffling because the null hypothesis assumed independence of the two variables. This process led to an empirical estimate of the sampling distribution, shown in <a href="#fig-hist224" class="quarto-xref">Figure&nbsp;<span>25.4</span></a>. Earlier in the chapter, using the Pearson’s chi-squared test, under the null hypothesis and the appropriate assumptions, the sampling distribution was a chi-squared distribution, shown by the dark blue line in the previous graph. We used it to calculate the <span class="math inline">\(p\)</span>-value directly.</p>
<p>Now that we’ve learned how to deal with two categorical variables, where at least one has more than two levels, we also want to consider situations where we have one categorical and one numerical variable.</p>
</section>
</section>
<section id="numerical-data" class="level2" data-number="25.5">
<h2 data-number="25.5" class="anchored" data-anchor-id="numerical-data"><span class="header-section-number">25.5</span> Numerical data</h2>
<p>Sometimes we want to compare means across groups. In this case, we have two variables, where one is continuous and the other is categorical. In this section, we will learn how to compare means for two different categories. We can do this using a randomization test, or using the CLT in what is called a two-sample <span class="math inline">\(t\)</span>-test. The hypotheses are:</p>
<p><span class="math inline">\(H_0\)</span>: The mean outcome is the same for both groups, or the difference in the means between the two groups is zero. In statistical notation, <span class="math inline">\(\mu_1 = \mu_2\)</span> or <span class="math inline">\(\mu_1 - \mu_2 = 0\)</span>, where <span class="math inline">\(\mu_1\)</span> represents the mean for group 1 and <span class="math inline">\(\mu_2\)</span> represents the mean for group 2.<br>
<span class="math inline">\(H_A\)</span>: The mean outcome for the two groups is different, or the difference in means is different from zero.</p>
<p>A two-sample <span class="math inline">\(t\)</span>-test can be used to test for a difference in two means when the following conditions are met:</p>
<ol type="i">
<li>The data in each group meet the conditions for using the <span class="math inline">\(t\)</span> distribution, i.e., the observations are independent and come from a nearly normal distribution.<br>
</li>
<li>The two groups are independent of each other.</li>
</ol>
<p>In general, the test statistic for a two-sample <span class="math inline">\(t\)</span>-test is:</p>
<p><span class="math display">\[
T = {\text{point estimate - null value} \over\text{standard error}} = {(\bar{X}_1 - \bar{X}_2) - 0 \over \sqrt{{S_1^2\over n_1} + {S_2^2\over n_2}}}
\]</span></p>
<p>The point estimate of interest is the difference between the sample means, and the null value is the hypothesized difference between the sample means, i.e., zero.</p>
<p>There are variations of this test statistic that use a pooled standard deviation or allow for paired, dependent, data, but these settings are beyond the scope of this book. We leave it to the reader to find out more about those situations as needed, and remind the reader that a lot of data analysis (and the associated code) is done via internet search.</p>
<p>When the null hypothesis (no difference in sample means) is true and the conditions are met, the test statistic <span class="math inline">\(T\)</span> has a <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(df \approx \min(n_1 - 1, n_2 - 1)\)</span>. More complicated calculations can be done to find the <em>exact</em> degrees of freedom, but this is again beyond the scope of this book. We leave it to the reader to find out more.</p>
<p>Let’s now turn to an example to illustrate this new statistical test.</p>
<section id="mlb-batting-performance" class="level3" data-number="25.5.1">
<h3 data-number="25.5.1" class="anchored" data-anchor-id="mlb-batting-performance"><span class="header-section-number">25.5.1</span> MLB batting performance</h3>
<p>We would like to discern whether there are real differences between the batting performance of baseball players according to their position. We will use a data set <code>mlbbat10</code> from the <strong>openintro</strong> package. It is available in the file <code>mlb_obp.csv</code> which has been modified from the original data set to include only those players with more than 200 at bats. The batting performance will be measured by on-base percentage, <code>obp</code>. The on-base percentage roughly represents the fraction of times a player successfully gets on base or hits a home run. There are four positions in the data, but we are only interested in outfielders (<code>OF</code>) and infielders (<code>IF</code>) for now.</p>
<p>Read the data into <code>R</code> and filter by position.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>mlb_obp_subset <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/mlb_obp.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(position <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"IF"</span>, <span class="st">"OF"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s review our data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">inspect</span>(mlb_obp_subset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
categorical variables:  
      name     class levels   n missing
1 position character      2 274       0
                                   distribution
1 IF (56.2%), OF (43.8%)                       

quantitative variables:  
  name   class   min   Q1 median    Q3   max     mean         sd   n missing
1  obp numeric 0.174 0.31  0.331 0.353 0.437 0.332719 0.03392522 274       0</code></pre>
</div>
</div>
<p>Next, change the variable <code>position</code> to a factor to make it easier to work with.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>mlb_obp_subset <span class="ot">&lt;-</span> mlb_obp_subset <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">position =</span> <span class="fu">as.factor</span>(position))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s look at summary statistics of the on-base percentage by position.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(obp <span class="sc">~</span> position, <span class="at">data =</span> mlb_obp_subset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  position   min      Q1 median      Q3   max     mean         sd   n missing
1       IF 0.174 0.30800 0.3270 0.35275 0.437 0.331526 0.03709504 154       0
2       OF 0.265 0.31475 0.3345 0.35300 0.411 0.334250 0.02944394 120       0</code></pre>
</div>
</div>
<p>The means for both groups are pretty similar to each other.</p>
<blockquote class="blockquote">
<p><strong>Exercise</strong>: The null hypothesis under consideration is the following: <span class="math inline">\(\mu_{OF} = \mu_{IF}\)</span> or <span class="math inline">\(\mu_{OF} - \mu_{IF} = 0\)</span>. Write the null and corresponding alternative hypotheses in plain language.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Exercise</strong>: If we have all the data for the 2010 season, why do we need a hypothesis test? What is the population of interest?<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Exercise</strong>:<br>
Construct side-by-side boxplots.</p>
</blockquote>
<p><a href="#fig-box225" class="quarto-xref">Figure&nbsp;<span>25.5</span></a> shows the side-by-side boxplots for infielders and outfielders.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-box225" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-box225-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Additional-Hypothesis-Tests_files/figure-html/fig-box225-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-box225-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;25.5: Boxplots of on-base percentage by position played.
</figcaption>
</figure>
</div>
</div>
</div>
<p>We must verify the assumptions before proceeding with a two-sample <span class="math inline">\(t\)</span>-test. We can assume that MLB players in 2010 are a representative sample of MLB players from other years. Also, the sample size for both groups is over 100, so we feel good about independence of observations within groups. There is no reason to believe that the data across groups, infielders versus outfielders, are not independent of each other. <a href="#fig-dens226" class="quarto-xref">Figure&nbsp;<span>25.6</span></a> and <a href="#fig-qq227" class="quarto-xref">Figure&nbsp;<span>25.7</span></a> show density curves and quantile-quantile plots for the on-base percentage by position played. There are no major outliers or other causes for concern. The data within each group appears nearly normal.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-dens226" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dens226-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Additional-Hypothesis-Tests_files/figure-html/fig-dens226-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dens226-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;25.6: Density curves of on-base percentage by position played.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-qq227" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-qq227-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Additional-Hypothesis-Tests_files/figure-html/fig-qq227-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qq227-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;25.7: Quantile-quantile plots of on-base percentage by position played.
</figcaption>
</figure>
</div>
</div>
</div>
<p>We can now move forward with a two-sample <span class="math inline">\(t\)</span>-test.</p>
<section id="test-statistic-1" class="level4" data-number="25.5.1.1">
<h4 data-number="25.5.1.1" class="anchored" data-anchor-id="test-statistic-1"><span class="header-section-number">25.5.1.1</span> Test statistic</h4>
<p>Our test statistic can be found using the summary statistics that we calculated earlier.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(obp <span class="sc">~</span> position, <span class="at">data =</span> mlb_obp_subset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  position   min      Q1 median      Q3   max     mean         sd   n missing
1       IF 0.174 0.30800 0.3270 0.35275 0.437 0.331526 0.03709504 154       0
2       OF 0.265 0.31475 0.3345 0.35300 0.411 0.334250 0.02944394 120       0</code></pre>
</div>
</div>
<p>We’ll treat infielders as group 1, subtracting their mean on-base percentage from that of outfielders. Thus, our observed test statistic is</p>
<p><span class="math display">\[
T = {(\bar{X}_{OF} - \bar{X}_{IF}) - 0 \over \sqrt{{S_{OF}^2\over n_{OF}} + {S_{IF}^2\over n_{IF}}}} = {(0.3343 - 0.3315) - 0 \over \sqrt{{0.0294^2\over 120} + {0.0371^2\over 154}}}
\]</span></p>
<p>We can also calculate this using <code>R</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">sd</span>(obp <span class="sc">~</span> position, <span class="at">data =</span> mlb_obp_subset)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> (<span class="fu">diffmean</span>(obp <span class="sc">~</span> position, <span class="at">data =</span> mlb_obp_subset) <span class="sc">-</span> <span class="dv">0</span>) <span class="sc">/</span> </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sqrt</span>(s[<span class="dv">2</span>]<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span><span class="dv">120</span> <span class="sc">+</span> s[<span class="dv">1</span>]<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span><span class="dv">154</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>obs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> diffmean 
0.6776293 </code></pre>
</div>
</div>
<p>Since the conditions for the <span class="math inline">\(t\)</span> distribution are met, under the null hypothesis, our test statistic has a <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(\min(120 - 1, 154 - 1) = 119\)</span> degrees of freedom.</p>
</section>
<section id="calculate-the-p-value." class="level4" data-number="25.5.1.2">
<h4 data-number="25.5.1.2" class="anchored" data-anchor-id="calculate-the-p-value."><span class="header-section-number">25.5.1.2</span> Calculate the p-value.</h4>
<p>We find the p-value for the two-sample <span class="math inline">\(t\)</span>-test by calculating the probability in the right tail of a <span class="math inline">\(t\)</span> distribution and doubling it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(obs, <span class="at">df =</span> <span class="dv">119</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> diffmean 
0.4993221 </code></pre>
</div>
</div>
</section>
<section id="draw-a-conclusion." class="level4" data-number="25.5.1.3">
<h4 data-number="25.5.1.3" class="anchored" data-anchor-id="draw-a-conclusion."><span class="header-section-number">25.5.1.3</span> Draw a conclusion.</h4>
<p>With such a large <span class="math inline">\(p\)</span>-value, we fail to reject the null hypothesis that the difference in means is zero. We do not have sufficient evidence to say that the mean on-base percentage for infielders and outfielders differs.</p>
</section>
</section>
<section id="two-sample-t-test-in-r" class="level3" data-number="25.5.2">
<h3 data-number="25.5.2" class="anchored" data-anchor-id="two-sample-t-test-in-r"><span class="header-section-number">25.5.2</span> Two-sample <span class="math inline">\(t\)</span>-test in <code>R</code></h3>
<p>As may be expected, we can also use the built-in <code>R</code> function <code>t_test()</code> that was previously discussed in <a href="Central-Limit-Theorem.html" class="quarto-xref"><span>Chapter 23</span></a>.</p>
<p>Here, we specify a formula with the numerical variable on the left and the categorical variable on the right. Remember to use <code>help(t_test)</code> or <code>?t_test</code> to access the <code>R</code> documentation for the <code>t_test</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t_test</span>(obp <span class="sc">~</span> position, <span class="at">data =</span> mlb_obp_subset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  obp by position
t = -0.67763, df = 271.9, p-value = 0.4986
alternative hypothesis: true difference in means between group IF and group OF is not equal to 0
95 percent confidence interval:
 -0.01063818  0.00519013
sample estimates:
mean in group IF mean in group OF 
        0.331526         0.334250 </code></pre>
</div>
</div>
<p>Our <span class="math inline">\(p\)</span>-value of 0.499 is very similar to the one we got using the <code>pt()</code> function. You should notice that the test statistic, <span class="math inline">\(t\)</span>, reported here is negative but has the same number value as our test statistic from before. The <code>t_test</code> function subtracted outfielders from infielders, but the <span class="math inline">\(p\)</span>-value is practically the same because of the symmetry of the <span class="math inline">\(t\)</span> distribution. If desired, we could reorder the levels of the <code>position</code> variable so that the results from <code>t_test()</code> more closely match our results from finding the <span class="math inline">\(p\)</span>-value directly. You should also notice that the degrees of freedom are much different than the 119 we used previously. The <code>t_test</code> function applies a Welch correction to the degrees of freedom (hence, the “Welch Two Sample t-test” title on the output above) in some situations. We leave the reader to investigate additional options in the <code>t_test()</code> function, as discussions of special cases of the two-sample <span class="math inline">\(t\)</span>-test are beyond the scope of this book.</p>
</section>
<section id="randomization-test" class="level3" data-number="25.5.3">
<h3 data-number="25.5.3" class="anchored" data-anchor-id="randomization-test"><span class="header-section-number">25.5.3</span> Randomization test</h3>
<p>We can repeat the same analysis using a randomization test. We will first use the difference of means as our test statistic, and then, for interest, we’ll use the <span class="math inline">\(t\)</span> statistic as well.</p>
<section id="test-statistic---difference-of-means" class="level4" data-number="25.5.3.1">
<h4 data-number="25.5.3.1" class="anchored" data-anchor-id="test-statistic---difference-of-means"><span class="header-section-number">25.5.3.1</span> Test statistic - difference of means</h4>
<p>Let’s calculate the observed test statistic.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> <span class="fu">diffmean</span>(obp <span class="sc">~</span> position, <span class="at">data =</span> mlb_obp_subset)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>obs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   diffmean 
0.002724026 </code></pre>
</div>
</div>
</section>
<section id="calculate-the-p-value-1" class="level4" data-number="25.5.3.2">
<h4 data-number="25.5.3.2" class="anchored" data-anchor-id="calculate-the-p-value-1"><span class="header-section-number">25.5.3.2</span> Calculate the p-value</h4>
<p>Now, we’ll conduct the randomization test. Under the null hypothesis, there is no difference in mean on-base percentage between infielders and outfielders. That is, the <code>position</code> label for each player can be shuffled around, and we should still end up with roughly equal mean on-base percentages. We’ll do this many times and plot the results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">807</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">1000</span>)<span class="sc">*</span><span class="fu">diffmean</span>(obp <span class="sc">~</span> <span class="fu">shuffle</span>(position), <span class="at">data =</span> mlb_obp_subset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><a href="#fig-hist228" class="quarto-xref">Figure&nbsp;<span>25.8</span></a> is a plot of the sampling distribution of the difference of means from the randomization test. The observed test statistic is shown as a red line.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-hist228" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hist228-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Additional-Hypothesis-Tests_files/figure-html/fig-hist228-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hist228-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;25.8: The sampling distribution of the randomization test using the difference of means.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The two-sided <span class="math inline">\(p\)</span>-value is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">prop1</span>(<span class="sc">~</span>(diffmean <span class="sc">&gt;=</span> obs), results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>prop_TRUE 
0.4895105 </code></pre>
</div>
</div>
<p>This is very similar to the <span class="math inline">\(p\)</span>-value we obtained using the two-sample <span class="math inline">\(t\)</span>-test.</p>
</section>
<section id="test-statistic---t" class="level4" data-number="25.5.3.3">
<h4 data-number="25.5.3.3" class="anchored" data-anchor-id="test-statistic---t"><span class="header-section-number">25.5.3.3</span> Test statistic - <span class="math inline">\(t\)</span></h4>
<p>Now, let’s repeat the analysis, but use the <span class="math inline">\(t\)</span> statistic as our test statistic. We’ll use the following code to extract the <span class="math inline">\(t\)</span> statistic from the <code>t_test()</code> output and find our observed test statistic.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> <span class="fu">t_test</span>(obp <span class="sc">~</span> position, <span class="at">data =</span> mlb_obp_subset)<span class="sc">$</span>statistic</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>obs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         t 
-0.6776293 </code></pre>
</div>
</div>
</section>
<section id="calculate-the-p-value-2" class="level4" data-number="25.5.3.4">
<h4 data-number="25.5.3.4" class="anchored" data-anchor-id="calculate-the-p-value-2"><span class="header-section-number">25.5.3.4</span> Calculate the p-value</h4>
<p>Now, we’ll conduct the randomization test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">526</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">1000</span>)<span class="sc">*</span><span class="fu">t_test</span>(obp <span class="sc">~</span> <span class="fu">shuffle</span>(position), <span class="at">data =</span> mlb_obp_subset)<span class="sc">$</span>statistic</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><a href="#fig-hist229" class="quarto-xref">Figure&nbsp;<span>25.9</span></a> is a plot of the sampling distribution of the <span class="math inline">\(t\)</span> statistic from the randomization test. The observed test statistic is shown as a red line. A <span class="math inline">\(t\)</span> distribution is overlaid as a dark blue line.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-hist229" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hist229-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Additional-Hypothesis-Tests_files/figure-html/fig-hist229-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hist229-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;25.9: The sampling distribution of the randomization test using the t-statistic.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The two-sided <span class="math inline">\(p\)</span>-value is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">prop1</span>(<span class="sc">~</span>(t <span class="sc">&lt;=</span> obs), results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>prop_TRUE 
0.5954046 </code></pre>
</div>
</div>
<p>You should notice that the <span class="math inline">\(p\)</span>-value for the two-sample <span class="math inline">\(t\)</span>-test is smaller than the <span class="math inline">\(p\)</span>-value obtained here. That is because the <span class="math inline">\(p\)</span>-value for the two-sample <span class="math inline">\(t\)</span>-test involves more assumptions. Still, our results here are consistent with those using the difference of means randomization test and the two-sample <span class="math inline">\(t\)</span>-test.</p>
</section>
</section>
<section id="paired-data" class="level3" data-number="25.5.4">
<h3 data-number="25.5.4" class="anchored" data-anchor-id="paired-data"><span class="header-section-number">25.5.4</span> Paired data</h3>
<p>Are textbooks actually cheaper online? In this example, we compare the price of textbooks at the University of California, Los Angeles’ (UCLA’s) bookstore and prices at Amazon.com. Seventy-three UCLA courses were randomly sampled in Spring 2010, representing less than 10% of all UCLA courses. When a class had multiple books, only the most expensive text was considered.</p>
<p>The data is in the file <code>textbooks.csv</code> under the data folder.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>textbooks <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/textbooks.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(textbooks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  dept_abbr course isbn           ucla_new amaz_new more   diff
  &lt;chr&gt;     &lt;chr&gt;  &lt;chr&gt;             &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
1 Am Ind    C170   978-0803272620     27.7     28.0 Y     -0.28
2 Anthro    9      978-0030119194     40.6     31.1 Y      9.45
3 Anthro    135T   978-0300080643     31.7     32   Y     -0.32
4 Anthro    191HB  978-0226206813     16       11.5 Y      4.48
5 Art His   M102K  978-0892365999     19.0     14.2 Y      4.74
6 Art His   118E   978-0394723693     15.0     10.2 Y      4.78</code></pre>
</div>
</div>
<p>Each textbook has two corresponding prices in the data set: one for the UCLA bookstore and one for Amazon. Therefore, each textbook price from the UCLA bookstore has a natural correspondence with a textbook price from Amazon. When two sets of observations have this special correspondence, they are said to be <strong>paired</strong>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Paired data examples
</div>
</div>
<div class="callout-body-container callout-body">
<p>Paired data arises when two related measurements are collected on the same individual, object, or entity, allowing for comparisons within each pair. Below are some examples of paired data, each involving a before-and-after or matched situation.</p>
<ul>
<li><p>Blood pressure is measured for patients before and after they take a new medication.</p></li>
<li><p>A company wants to test two different training programs for employee productivity. Each employee undergoes both training programs, one after the other, in a randomized order.</p></li>
<li><p>A school measures students’ test scores before and after a study skills intervention.</p></li>
<li><p>A psychological study measures stress levels in identical twins, with one twin assigned to a stress-reduction program and the other twin lives their life as normal.</p></li>
<li><p>A new mosquito repellent is tested on subjects, with one arm being sprayed with the new product and the other not.</p></li>
</ul>
</div>
</div>
<p>To analyze paired data, it is often useful to look at the difference in outcomes of each pair of observations. In <code>textbooks</code>, we look at the difference in prices, which is represented as the <code>diff</code> variable. It is important that we always subtract using a consistent order; here Amazon prices are always subtracted from UCLA prices.</p>
<p>This data is tidy, because each row is a textbook and each column is a variable. We first make a scatterplot of the UCLA price versus the Amazon price. We’ll add a 45 degree line to the plot, indicating where both prices are the same.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>textbooks <span class="sc">%&gt;%</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_point</span>(ucla_new<span class="sc">~</span>amaz_new) <span class="sc">%&gt;%</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_abline</span>(<span class="at">slope=</span><span class="dv">1</span>,<span class="at">intercept =</span> <span class="dv">0</span>,<span class="at">color=</span><span class="st">"darkblue"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_theme</span>(<span class="fu">theme_classic</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(<span class="at">x=</span><span class="st">"Amazon"</span>,<span class="at">y=</span><span class="st">"UCLA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Additional-Hypothesis-Tests_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It appears the books at the UCLA bookstore are more expensive. One way to test this is with a regression model; we will learn more about this method in the next block.</p>
<p>A density plot of the differences in price shows us that the distribution is right skewed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>textbooks <span class="sc">%&gt;%</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_dens</span>(<span class="sc">~</span>diff,<span class="at">fill=</span><span class="st">"cyan"</span>,<span class="at">color=</span><span class="st">"black"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_theme</span>(<span class="fu">theme_classic</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(<span class="at">title=</span><span class="st">"Distribution of price differences"</span>,</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">x=</span><span class="st">"Price difference between UCLA and Amazon"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Additional-Hypothesis-Tests_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The hypotheses are:</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_{diff}=0\)</span>. There is no difference in the average textbook price.<br>
<span class="math inline">\(H_A\)</span>: <span class="math inline">\(\mu_{diff} \neq 0\)</span>. There is a difference in average textbook prices.</p>
<p>To use a <span class="math inline">\(t\)</span> distribution, the variable <code>diff</code> has to be independent and normally distributed. Since the 73 books represent less than 10% of the population and UCLA courses were randomly sampled, the assumption that the random sample is independent is reasonable. We can check normality using a quantile-quantile plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_qq</span>(<span class="sc">~</span>diff, <span class="at">data =</span> textbooks) <span class="sc">%&gt;%</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_qqline</span>(<span class="sc">~</span>diff, <span class="at">data =</span> textbooks) <span class="sc">%&gt;%</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_theme</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Additional-Hypothesis-Tests_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The normality assumption is suspect but we have a large sample so it should be acceptable to use the <span class="math inline">\(t\)</span>.</p>
<section id="paired-t-test" class="level4" data-number="25.5.4.1">
<h4 data-number="25.5.4.1" class="anchored" data-anchor-id="paired-t-test"><span class="header-section-number">25.5.4.1</span> Paired <span class="math inline">\(t\)</span>-test</h4>
<p>Let’s run a paired <span class="math inline">\(t\)</span>-test on the <code>diff</code> variable. We can use the <code>t_test()</code> function in <code>R</code> for this. Note that we do not have to use the <code>paired=TRUE</code> option because we already took the difference in prices.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t_test</span>(<span class="sc">~</span>diff, <span class="at">data =</span> textbooks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  diff
t = 7.6488, df = 72, p-value = 6.928e-11
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
  9.435636 16.087652
sample estimates:
mean of x 
 12.76164 </code></pre>
</div>
</div>
<p>We can conduct the same paired <span class="math inline">\(t\)</span>-test using the two price variables and <code>paired=TRUE</code>, shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t_test</span>(textbooks<span class="sc">$</span>ucla_new, textbooks<span class="sc">$</span>amaz_new, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  textbooks$ucla_new and textbooks$amaz_new
t = 7.6488, df = 72, p-value = 6.928e-11
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
  9.435636 16.087652
sample estimates:
mean difference 
       12.76164 </code></pre>
</div>
</div>
<p>The <span class="math inline">\(p\)</span>-value is extremely small, leading us to reject the null hypothesis and conclude that there is a difference in the average textbook prices. We don’t believe the average price of the books from the UCLA bookstore and Amazon are the same.</p>
</section>
<section id="randomization-test-1" class="level4" data-number="25.5.4.2">
<h4 data-number="25.5.4.2" class="anchored" data-anchor-id="randomization-test-1"><span class="header-section-number">25.5.4.2</span> Randomization test</h4>
<p>We can also conduct a randomization test on this data using the difference of paired means as our test statistic. The observed test statistic is the mean of the paired differences.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>obs_stat <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="sc">~</span>diff, <span class="at">data =</span> textbooks)  </span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>obs_stat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.76164</code></pre>
</div>
</div>
<p>To conduct the randomization, we have to be careful. We want to keep the pairings so we can’t just shuffle the names/labels (UCLA or Amazon). We have to shuffle the names within the pairs. We simply want to randomly switch the names within a row. This is easiest to do by multiplying the <code>diff</code> column by a random choice of -1 and 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>), <span class="at">size =</span> <span class="dv">73</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  1 -1  1  1 -1  1  1 -1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1 -1 -1 -1  1
[26]  1 -1 -1 -1 -1  1 -1 -1  1 -1 -1  1  1  1 -1 -1  1  1  1 -1  1 -1  1 -1 -1
[51] -1 -1  1  1  1  1 -1  1 -1  1 -1 -1 -1 -1  1 -1 -1  1 -1 -1  1  1 -1</code></pre>
</div>
</div>
<p>We’ll set a seed and generate 1,000 randomizations. In each, we randomly choose -1 or 1 to multiply by the difference in prices. We’ll then take the mean of the differences.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">406</span>) </span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">1000</span>)<span class="sc">*</span><span class="fu">mean</span>((<span class="sc">~</span>diff<span class="sc">*</span><span class="fu">sample</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>), <span class="at">size =</span> <span class="dv">73</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)), </span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> textbooks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We plot a histogram of the results and include our observed mean of paired differences as a vertical red line.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>results <span class="sc">%&gt;%</span>   </span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_histogram</span>(<span class="sc">~</span>mean, <span class="at">fill =</span> <span class="st">"cyan"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">%&gt;%</span>  </span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_stat, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_theme</span>(<span class="fu">theme_classic</span>()) <span class="sc">%&gt;%</span>   </span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(<span class="at">title =</span> <span class="st">"Randomization sampling distribution of mean of differences in price"</span>,           </span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">x =</span> <span class="st">"Mean of price difference"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Additional-Hypothesis-Tests_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The <span class="math inline">\(p\)</span>-value is the probability of an observed mean difference of 12.76 or something more extreme, if the null hypothesis is really true. The plot above implies that our <span class="math inline">\(p\)</span>-value will be very small (because the observed mean difference is so far out to the right), but we’ll verify by calculating the <span class="math inline">\(p\)</span>-value. Because this is a two-sided hypothesis test, we double the probability.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">prop</span>((<span class="sc">~</span>mean <span class="sc">&gt;=</span> obs_stat), <span class="at">data =</span> results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>prop_TRUE 
        0 </code></pre>
</div>
</div>
<p>None of the simulated values is at or greater than the observed value. Using <code>prop1()</code> is often preferred, because it includes the observed test statistic in the proportion, so we never end up with exactly zero.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">prop1</span>((<span class="sc">~</span>mean <span class="sc">&gt;=</span> obs_stat), <span class="at">data =</span> results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  prop_TRUE 
0.001998002 </code></pre>
</div>
</div>
<p>With a <span class="math inline">\(p\)</span>-value of 0.002, we reject the null hypothesis and conclude that the mean of paired differences is different from zero. That is, there is a difference in the average price of textbooks from the UCLA bookstore and Amazon.</p>
</section>
<section id="using-the-binomial-distribution" class="level4" data-number="25.5.4.3">
<h4 data-number="25.5.4.3" class="anchored" data-anchor-id="using-the-binomial-distribution"><span class="header-section-number">25.5.4.3</span> Using the binomial distribution</h4>
<p>We can also approach this problem using known probability distributions. If there is really no difference between book sources, the variable <code>more</code> (“Y” for yes and “N” for no) can be viewed as a binomial random variable. Under the null hypothesis, the probability of success (UCLA textbooks costing more than Amazon) is <span class="math inline">\(\pi = 0.5\)</span>.</p>
<p>Let’s conduct a hypothesis test using the variable <code>more</code>. The hypotheses are:</p>
<p><span class="math inline">\(H_0: \pi = 0.5\)</span>, the probability of UCLA textbooks costing more than Amazon is 0.5. <span class="math inline">\(H_A: \pi\neq 0.5\)</span>, the probability of UCLA textbooks costing more than Amazon is different from 0.5.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(<span class="sc">~</span>more, <span class="at">data =</span> textbooks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>more
 N  Y 
28 45 </code></pre>
</div>
</div>
<p>We have 45 textbooks that were more expensive from the UCLA bookstore than Amazon, out of the total of 73. The <span class="math inline">\(p\)</span>-value is the probability that 45 or more textbooks were more expensive. We can use <code>pbinom()</code> to calculate this probability and we multiply by two because we are conducting a two-sided hypothesis test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pbinom</span>(<span class="dv">44</span>, <span class="at">size =</span> <span class="dv">73</span>, <span class="at">prob =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.06037004</code></pre>
</div>
</div>
<p>We can also use <code>prop_test()</code> to find a very similar <span class="math inline">\(p\)</span>-value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop_test</span>(<span class="at">x =</span> <span class="dv">45</span>, <span class="at">n =</span> <span class="dv">73</span>, <span class="at">p =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1-sample proportions test with continuity correction

data:  45 out of 73
X-squared = 3.5068, df = 1, p-value = 0.06112
alternative hypothesis: true p is not equal to 0.5
95 percent confidence interval:
 0.4948968 0.7256421
sample estimates:
        p 
0.6164384 </code></pre>
</div>
</div>
<p>Because our <span class="math inline">\(p\)</span>-value is larger than the significance level of <span class="math inline">\(\alpha = 0.05\)</span>, we fail to reject the null hypothesis. There is not enough evidence to say that the probability of UCLA textbooks costing more than Amazon is different from 0.5. In the paired test, the evidence was extremely convincing but in the binomial model it is not. There is a loss of information when we make a discrete variable out of a continuous one.</p>
<p>In the next chapter, we will learn how to use the <span class="math inline">\(F\)</span> statistic and analysis of variance (ANOVA) to test whether there are differences among more than two means simultaneously.</p>


</section>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p><span class="math inline">\(H_0\)</span>: The average on-base percentage for infielders and outfielders is equal, or the average difference between on-base percentage for infielders and outfielders is zero. <span class="math inline">\(H_A\)</span>: The average on-base percentage for infielders and outfielders is different.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>If we are only making decisions or claims about the 2010 season, we do not need hypothesis testing. We can simply use summary statistics. However, if we want to generalize to other years or other leagues, then we need to conduct a hypothesis test.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Confidence-Intervals.html" class="pagination-link" aria-label="Confidence Intervals">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Confidence Intervals</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Analysis-of-Variance.html" class="pagination-link" aria-label="Analysis of Variance">
        <span class="nav-page-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Computation Probability and Statistics by Hitt, Horton, and Warner</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/DS-USAFA/Quarto-Book/edit/main/Additional-Hypothesis-Tests.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>